name: Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  test:

    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Publish the release to npm
      - uses: ./.github/actions/npm-publish
        with:
          require-build: true
          
      # Publish the release to npm
      - uses: ./.github/actions/npm-publish
        with:
          require-build: false
